# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'rubygems'
require 'spork'

Spork.prefork do
  #need to do this explicitly, otherwise the env somehow gets set back to 'test' and the wrong environment config is used
  ENV["RAILS_ENV"] = "cucumber"
  
  require File.expand_path(File.dirname(__FILE__) + '/../../config/environment')

  require 'cucumber/formatter/unicode' # Remove this line if you don't want Cucumber Unicode support
  require 'cucumber/rails/rspec'
  require 'cucumber/rails/world'
  require 'cucumber/rails/active_record'
  require 'cucumber/web/tableish'
  require 'email_spec'
  require 'email_spec/cucumber'


  require 'webrat'
  require 'webrat/core/matchers'

  Webrat.configure do |config|
    config.mode = :rails
    config.open_error_files = false # Set to true if you want error pages to pop up in the browser
  end


end

Spork.each_run do
  ActionController::Base.allow_rescue = false

  Cucumber::Rails::World.use_transactional_fixtures = true

  require 'database_cleaner'
  DatabaseCleaner.strategy = :truncation

end
